### ISSUE TITLE
Generate mocks from OpenAPI document

### ISSUE THREAD

**Issue by jeroenherczeg** [fauxauldrich/camouflage#35]
OpenAPI is a description of HTTP-based APIs which are typically, RESTful APIs. It comes in the form of a YAML file or JSON, that describes the inputs and outputs of an API. OpenAPI is not the only way to describe a API, there is also RAML, API Blueprint, ... but it looks like OpenAPI is becoming the standard. More information can be found https://www.openapis.org/. https://spec.openapis.org/oas/v3.1.0

When using a Contract-First API Development approach, our first task is to describe an API with OpenAPI before starting to code. The next step would be to launch the API using a mock service/service virtualization. So consumers can already work with the service while it is under development.

The mock service/service virtualization is also used for running integration testing, so when we test a service, we use the mocks for the dependent services.

It would be great if we could use these documents to generate the necessary files and folders for Camouflage. Camouflage is very simple to use and I would be great to keep it this way. So maybe a solution would be to not include this feature inside camouflage but to provide a separate way to generate the necessary files. 

The current version of OpenAPI is 3.1, which came out in 15 Feb 2021, but the tooling supporting OAS3.1 is still under development (a parser is probably needed). Most tooling supports up to OAS3.0.

There is also an example object which could be used to provide data for the mocks: https://spec.openapis.org/oas/v3.1.0#example-object

Note: There is also a spec for asynchronous APIs called AsyncAPI (which is heavily based on OpenAPI) and is used to describe for instance WebSocket communication.

**Comment by shubhendumadhukar** [comment]
Thanks @jeroenherczeg for the detailed description and the resources. To be honest, I haven't worked with OpenAPI specs much so the resources were specially helpful. Also the suggestion that this should be an external utility and not something bundled with Camouflage, was on point.

Here's an update from my end. I already have a working prototype of the conversion utility.
- The utility takes in a spec file via command like parameter -s/--spec. And the location of the current mocks directory via -m/--mock.
- It validates if files exists.
- If the file exists, it checks if the input file is a valid OpenAPI definition
- If that check too passes, it replaces all the path parameters with wildcards.
- In final step, it created the mock files for each path specified in spec file.

A generic format of the files created is:
`${MOCKS_DIR}/${PATH}/${METHOD}.mock`
where:
- ${MOCKS_DIR} is the path of mocks directory specified by -m/--mocks parameter;
- ${PATH} is the individual path element from the array of url paths extracted from spec file (path parameters replaced with wildcards)
- ${METHOD} is the HTTP Method for each url extracted from the spec file

Since I couldn't find this information anywhere, could you please help answer following query?

Is there a way we can populate the contents of the mock files too? Does the spec file also contain the expected responses for the specified URLs? If yes, would you be able help with an example?

**Comment by jeroenherczeg** [comment]
Example: https://gist.github.com/jeroenherczeg/ae76732cca9c2e078a3e466829b47b3a

So for the path '/users/{userId}' we define a GET and a PATCH.

In the request we require query parameter called userId.

The GET request has 2 responses a 200 and a 404.
The 200 also returns a body in json.
This document has example data.

```
{
    "id": 142,
    "firstName": "Alice",
    "lastName": "Smith",
    "email": "alice.smith@gmail.com",
    "dateOfBirth": "1997-10-31",
    "emailVerified": true,
    "signUpDate": "2019-08-24"
}
```
Examples are optional, but there is always a schema object defining the response body.
This could be inline under schema or could be by ref like in the example $ref: '#/components/schemas/User'

```
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
        - id: 143
          firstName: John
          lastName: Doe
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
  ```
If you need help let me know!
